name: Build Android

on:
  push:
    paths:
      - 'frontend/guideo-app/**'

jobs:
  build-android:
    name: Building Android apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
          working-directory: frontend/guideo-app
      - run: expo build:android
          working-directory: frontend/guideo-app
