name: Build Android

on:
  push:
    paths:
      - 'frontend/guideo-app/**'

jobs:
  build-android:
    name: Building Android apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Yarn Install
        run: yarn install
        working-directory: frontend/guideo-app
      - name: Build Android
        run: cd frontend/guideo-app && expo build:android